{% set version = "3.2.0" %}

package:
  name: jupyterlab-fasta
  version: 3.2.0

source:
  url: https://pypi.io/packages/source/j/jupyterlab-fasta/jupyterlab-fasta-{{ version }}.tar.gz
  sha256: e9ce735b59bf25a0882dd8fdfe0de4b612e1890adf96eef859ae259b2bedc2b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - jupyterlab >=3,<4
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyterlab/fasta-extension.*{{ version }}.*ok.*jupyterlab-fasta" labextensions
  requires:
    - pip
    - jupyterlab >=3.0,<4
    - m2-grep  # [win]

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: Fasta renderer for JupyterLab
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - jupyterlab-fasta/labextension/static/third-party-licenses.json

extra:
  recipe-maintainers:
    - fcollonval
    - jtpio
    - jasongrout
    - blink1073
    - bollwyvl
